FROM node:20-slim AS builder

WORKDIR /app

COPY services/web/package*.json ./
RUN npm install

COPY services/web/ .
RUN npm run build

FROM node:20-slim AS runner

WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]
