apiVersion: v2
name: job-agent
description: A Helm chart for Talent Acquisition Agent (Job Agent)
type: application
version: 0.1
appVersion: 0.1
keywords:
  - job
  - recruitment
  - talent
  - agent
maintainers:
  - name: Job Agent Team
    email: team@jobagent.dev
